version: '3.8'

services:
  web:
    build:
      context: .
    image: custom-php:8.2-apache
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./apache-config:/etc/apache2/sites-enabled
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html
    working_dir: /var/www/html
    command: >
      bash -c "
      a2enmod rewrite && \
      apache2-foreground"
    restart: always
    networks:
      - internal-network

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root123
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    networks:
      - internal-network

volumes:
  db_data:

networks:
  internal-network:
    driver: bridge