version: '3.8'

services:
  web:
    build:
      context: .
    image: custom-php:8.2-apache
    container_name: web_${COMPOSE_PROJECT_NAME}
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./core/apache-config:/etc/apache2/sites-enabled
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html
    working_dir: /var/www/html
    command: >
      bash -c "
      a2enmod rewrite && \
      apache2-foreground"
    restart: always
    networks:
      internal-network:
        aliases:
          - web_${COMPOSE_PROJECT_NAME}

  db:
    image: mysql:8.0
    container_name: db_${COMPOSE_PROJECT_NAME}
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root123
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    networks:
      internal-network:
        aliases:
          - db_${COMPOSE_PROJECT_NAME}

volumes:
  db_data:

networks:
  internal-network:
    driver: bridge
